from __future__ import annotations

import argparse
import csv
import itertools
import json
from datetime import datetime, timezone
from pathlib import Path
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]
MAIN_PY = ROOT / "main.py"
CONFIG_YAML = ROOT / "configs" / "pilot" / "eomt_lora_pilot.yaml"
OUT_DIR = ROOT / "runs"


def _cli_arg_value(value: str | dict | list | int | float | bool) -> str:
    """Formats Python primitives and dicts into valid LightningCLI flags."""
    if isinstance(value, (dict, list, tuple)):
        return json.dumps(value)
    if isinstance(value, bool):
        return str(value).lower()
    return str(value)


def parse_last_metrics(run_dir: Path) -> dict[str, float] | None:
    """Finds and parses the latest metrics.csv generated by PyTorch Lightning CSVLogger."""
    csv_paths = sorted(run_dir.rglob("metrics.csv"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not csv_paths:
        return None

    metrics_map: dict[str, float] = {}
    try:
        with open(csv_paths[0], "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                for k, v in row.items():
                    if v not in ("", None) and k not in ("epoch", "step", "_step", "timestamp"):
                        try:
                            metrics_map[k] = float(v)
                        except ValueError:
                            pass
    except Exception:
        return None

    return metrics_map if metrics_map else None


def build_cmd(
    run_name: str,
    model_overrides: dict,
    limit_train_batches: float | int = 1,
    limit_val_batches: float | int = 1,  # Added parameter (defaults to 1 batch)
    pilot_logs: str | None = None,
) -> list[str]:
    """Constructs the command list for spawning a main.py fit run."""
    cmd = ["python", str(MAIN_PY), "fit", "-c", str(CONFIG_YAML)]

    logger_cfg = {
        "class_path": "lightning.pytorch.loggers.CSVLogger",
        "init_args": {
            "name": run_name,
            "save_dir": str(pilot_logs) if pilot_logs else "pilot_logs",
        },
    }
    cmd += ["--trainer.logger", json.dumps(logger_cfg)]

    # Trainer limits
    cmd += ["--trainer.limit_val_batches", _cli_arg_value(limit_val_batches)]
    cmd += ["--trainer.limit_train_batches", _cli_arg_value(limit_train_batches)]

    # Model overrides
    for k, v in model_overrides.items():
        cmd += [f"--model.init_args.{k}", _cli_arg_value(v)]

    return cmd


def main():
    parser = argparse.ArgumentParser(description="Run hyperparameter & dataset scaling sweep")
    parser.add_argument("--out", default=str(OUT_DIR), help="Output directory for runs")
    parser.add_argument("--dry", action="store_true", help="Print commands without executing")
    parser.add_argument("--sweep-name", default=None, help="Name for grouped sweep subfolder")
    parser.add_argument(
        "--dataset-pcts",
        nargs="+",
        type=float,
        default=[1.0],
        help="Training dataset fractions to sweep over (e.g., 0.05 0.25 1.0)",
    )
    # ADD THESE TWO ARGUMENTS:
    parser.add_argument("--limit-train-batches", type=int, default=20, help="Number of train batches")
    parser.add_argument("--limit-val-batches", type=int, default=10, help="Number of val batches")
    args = parser.parse_args()

    if args.sweep_name:
        base = (ROOT / "sweeps" / args.sweep_name).resolve()
        pilot_logs_root = base / "pilot_logs"
        out_dir = base / "runs"
        pilot_logs_root.mkdir(parents=True, exist_ok=True)
        out_dir.mkdir(parents=True, exist_ok=True)
        if CONFIG_YAML.exists():
            shutil.copy(CONFIG_YAML, out_dir / CONFIG_YAML.name)
    else:
        out_dir = Path(args.out).resolve()
        out_dir.mkdir(parents=True, exist_ok=True)
        pilot_logs_root = (ROOT / "pilot_logs").resolve()

    timestamp_str = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    all_vit_blocks = ",".join(str(i) for i in range(12))

    regime_configs = [
        {
            "name": "full-finetune",
            "model_init_base": {"freeze_backbone": False, "lora_enabled": False},
            "lrs": [1e-4],
            "weight_decays": [0.05],
        },
        #{
        #    "name": "lora-tune",
        #    "model_init_base": {"freeze_backbone": True, "lora_enabled": True},
        #    "lrs": [5e-5],
        #    "weight_decays": [0.05],
        #    "ranks": [16],
        #    "alphas": [16.0],
        #},
    ]

    runs = []
    for pct in args.dataset_pcts:
        pct_suffix = f"_pct{int(pct * 100)}" if len(args.dataset_pcts) > 1 or pct != 1.0 else ""

        for regime in regime_configs:
            regime_name = regime["name"]
            base_init = regime["model_init_base"]

            if base_init.get("lora_enabled"):
                for lr, wd, r, a in itertools.product(
                    regime["lrs"], regime["weight_decays"], regime["ranks"], regime["alphas"]
                ):
                    run_name = f"{regime_name}_lr{lr}_wd{wd}_r{r}_a{int(a)}{pct_suffix}_{timestamp_str}"
                    model_overrides = {
                        **base_init,
                        "lr": lr,
                        "weight_decay": wd,
                        "lora_config": {
                            all_vit_blocks: {"rank": r, "alpha": float(a), "modules": ["qkv", "proj"]}
                        },
                    }
                    runs.append((run_name, model_overrides, pct))
            else:
                for lr, wd in itertools.product(regime["lrs"], regime["weight_decays"]):
                    run_name = f"{regime_name}_lr{lr}_wd{wd}{pct_suffix}_{timestamp_str}"
                    model_overrides = {**base_init, "lr": lr, "weight_decay": wd}
                    runs.append((run_name, model_overrides, pct))

    summary = []
    for run_name, model_overrides, pct in runs:
        print(f"\n[Sweep Execution] Launching: {run_name} (Train Pct: {pct * 100:.1f}%)")

        # PASS THE INT VALUES EXPLICITLY:
        cmd = build_cmd(
            run_name,
            model_overrides,
            limit_train_batches=args.limit_train_batches,  # Integer 20
            limit_val_batches=args.limit_val_batches,  # Integer 10
            pilot_logs=str(pilot_logs_root),
        )
        log_file = out_dir / f"{run_name}.log"

        if args.dry:
            print(f"Dry run command: {' '.join(cmd)}")
            continue

        before_dirs = {p.resolve() for p in pilot_logs_root.glob("**/*") if p.is_dir()}

        with open(log_file, "wb") as lf:
            proc = subprocess.Popen(cmd, stdout=lf, stderr=subprocess.STDOUT, cwd=str(ROOT))
            ret = proc.wait()

        after_dirs = sorted(
            [p.resolve() for p in pilot_logs_root.glob("**/*") if p.is_dir()],
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        new_dirs = [d for d in after_dirs if d not in before_dirs]
        candidate_dir = new_dirs[0] if new_dirs else (after_dirs[0] if after_dirs else None)

        metrics = parse_last_metrics(candidate_dir) if candidate_dir else None

        summary.append({
            "run_name": run_name,
            "dataset_pct": pct,
            "cmd": cmd,
            "return_code": ret,
            "metrics": metrics,
            "log": str(log_file),
            "run_dir": str(candidate_dir) if candidate_dir else None,
        })

        summary_path = out_dir / "sweep_summary.json"
        with open(summary_path, "w", encoding="utf-8") as f:
            json.dump(summary, f, indent=2)

        print(f"Run {run_name} finished (exit code={ret}). Log: {log_file}")

    print(f"\nSweep completed. Summary saved to: {out_dir / 'sweep_summary.json'}")


if __name__ == "__main__":
    main()